### ISSUE TITLE
Provide Option 'restrictedToMinimumLevel'

### ISSUE THREAD

**Issue by 7enderhead** [manigandham/serilog-sinks-fastconsole#1]
- useful for, e.g., logging only warnings to console and all debug stuff to file
- standard console sink supports this:
```fsharp
let logger =
        LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.File(logfileName, shared = true, restrictedToMinimumLevel = LogEventLevel.Debug)
            .WriteTo.Console(restrictedToMinimumLevel = LogEventLevel.Warning)
            .CreateLogger()
```

**Comment by manigandham** [comment]
hi @7enderhead 

sorry I didn't see earlier, I've updated the library with that parameter: https://www.nuget.org/packages/Serilog.Sinks.FastConsole/1.4.0
