### ISSUE TITLE
Add option to block if queue is full?

### ISSUE THREAD

**Issue by mamort** [manigandham/serilog-sinks-fastconsole#7]
It would be nice to have an option to block when log queue is full to avoid losing log messages if blocking is preferred. Like this:
```
    public void Emit(LogEvent logEvent) {
        if (_options.blockWhenFull)
        {
            _writeQueue.Writer.WriteAsync(logEvent).GetAwaiter().GetResult();
        }
        else
        {
            _writeQueue.Writer.TryWrite(logEvent);
        }
    }

**Comment by sungam3r** [comment]
@mamort In #8 I use a bit different approach. Also note that `GetAwaiter().GetResult()` SHOULD NOT be called on `ValueTask`. Your code yields [ca2012](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2012) analyzer warning. See https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/:
> If you have a ValueTask or a ValueTask<TResult> and you need to do one of these things, you should use .AsTask() to get a Task / Task<TResult> and then operate on that resulting task object.

**Comment by mamort** [comment]
Thanks for the info on ValueTask. Wasn't aware of that. Your implementation is better :thumbsup:

**Comment by manigandham** [comment]
@mamort new version released: https://www.nuget.org/packages/Serilog.Sinks.FastConsole/2.2.0
